name: Deploy SQL to MSSQL
 
on: [push]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy SQL to MSSQL
      env:
        MSSQL_HOST: ${{ secrets.MSSQL_HOST }}
        MSSQL_USER: ${{ secrets.MSSQL_USER }}
        MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
      run: |
        echo "CREATE TABLE test (id INT, name VARCHAR(50));" > create_test_table.sql
        sqlcmd -S $MSSQL_HOST -U $MSSQL_USER -P $MSSQL_PASSWORD -d actions1 -i create_test_table.sql
