name: Deploy SQL to MSSQL2

on:
  push:
    paths:
      - '**.sql'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy SQL to MSSQL
        env:
          MSSQL_HOST: ${{ secrets.MSSQL_HOST }}
          MSSQL_USER: ${{ secrets.MSSQL_USER }}
          MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
        run: |
          for file in $(find . -name '*.sql'); do
            sqlcmd -S $MSSQL_HOST -U $MSSQL_USER -P $MSSQL_PASSWORD -d actions1 -b -o /dev/null -i $file
          done
