name: sql_mssql

on:
  push:
    paths:
      - '**.sql'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run split_sql.sh
        run: |
          chmod +x ./split_sql.sh
          ./split_sql.sh actions1/person.sql

      - name: Deploy SQL to MSSQL
        env:
          MSSQL_HOST: ${{ secrets.MSSQL_HOST }}
          MSSQL_USER: ${{ secrets.MSSQL_USER }}
          MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
        run: |
          for file in $(find . -name '*.sql'); do
            sqlcmd -S $MSSQL_HOST -U $MSSQL_USER -P $MSSQL_PASSWORD -d actions1 -i $file -o /dev/null
          done
